apiVersion: v1
kind: ConfigMap
metadata:
  name: snowy-xxl-job-app-config
  labels:
    app: snowy-xxl-job-app
data:
  # Nacos 配置（默认值，可被 overlays 覆盖）
  nacos.server.addr: "snowy-nacos-app.infra.svc.cluster.local:8848"
