apiVersion: v1
kind: Service
metadata:
  name: snowy-xxl-job-app
  labels:
    app: snowy-xxl-job-app
spec:
  type: ClusterIP
  ports:
  - port: 9004
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: snowy-xxl-job-app
