apiVersion: v1
kind: Service
metadata:
  name: snowy-gateway-app
  labels:
    app: snowy-gateway-app
spec:
  type: ClusterIP
  ports:
  - port: 9003
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: snowy-gateway-app
