apiVersion: v1
kind: ConfigMap
metadata:
  name: snowy-nacos-app-config
  labels:
    app: snowy-nacos-app
data:
  # Nacos basic configuration
  nacos.standalone: "true"
  nacos.core.auth.enabled: "false"
  server.tomcat.basedir: "file:./logs"
  server.port: "8848"
  spring.sql.init.platform: "mysql"
  db.num: "1"
