apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resource list
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

# Image tag (can be overridden in overlays)
images:
  - name: snowy-nacos-app
    newTag: latest
