apiVersion: v1
kind: Service
metadata:
  name: snowy-nacos-app
  labels:
    app: snowy-nacos-app
spec:
  type: ClusterIP
  ports:
  - port: 8848
    targetPort: http
    protocol: TCP
    name: http
  - port: 9848
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    app: snowy-nacos-app
