apiVersion: v1
kind: Service
metadata:
  name: snowy-sentinel-app
  labels:
    app: snowy-sentinel-app
spec:
  type: ClusterIP
  ports:
  - port: 9002
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: snowy-sentinel-app
