apiVersion: v1
kind: Service
metadata:
  name: snowy-actuator-app
  labels:
    app: snowy-actuator-app
spec:
  type: ClusterIP
  ports:
  - port: 9001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: snowy-actuator-app
