apiVersion: v1
kind: Secret
metadata:
  name: snowy-nacos-app-secret
  labels:
    app: snowy-nacos-app
type: Opaque
stringData:
  # Nacos 连接外部 MySQL 配置
  # MySQL Service 名称: mysql-service
  # 数据库名称: nacos
  db-url: "jdbc:mysql://mysql:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  db-user: "nacos"
  db-password: "nacos123!@#"
