apiVersion: v1
kind: Service
metadata:
  name: snowy-biz-app
  labels:
    app: snowy-biz-app
spec:
  type: ClusterIP
  ports:
  - port: 9102
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: snowy-biz-app
