apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 开发环境命名空间
namespace: infra

# 引用基础配置
resources:
  - ../../base
  - ingress.yaml

# 策略合并补丁
patches:
  - path: deployment-patch.yaml

# ConfigMap 生成器（合并 base 中的 configmap）
configMapGenerator:
  - name: snowy-actuator-app-config
    behavior: merge
    literals:
      - spring.profiles.active=dev

# 镜像标签
images:
  - name: snowy-actuator-app
    newTag: latest
