apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowy-xxl-job-app-ingress
  namespace: production
  annotations:
    # 生产环境可启用 SSL
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: xxl-job.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: snowy-xxl-job-app
            port:
              number: 9004
