apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Development environment namespace
namespace: infra

# Reference base configuration
resources:
  - ../../base
  - ingress.yaml

# Strategic merge patch
patches:
  - path: deployment-patch.yaml

# ConfigMap generator (merge with base configmap)
configMapGenerator:
  - name: snowy-gateway-app-config
    behavior: merge
    literals:
      - spring.profiles.active=dev

# Image tag
images:
  - name: snowy-gateway-app
    newTag: latest
