apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 资源列表
resources:
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

# 镜像标签（可在 overlays 中覆盖）
images:
  - name: snowy-web-app
    newTag: latest
