apiVersion: v1
kind: Service
metadata:
  name: snowy-web-app
  labels:
    app: snowy-web-app
spec:
  type: ClusterIP
  ports:
  - port: 9101
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: snowy-web-app
