# Kustomization for Snowy Admin Web - Base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend

resources:
  - namespace.yaml
  - gateway-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-doc.yaml

images:
  - name: snowy-admin-web
    newTag: latest
