apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 生产环境命名空间
namespace: production

# 引用基础配置
resources:
  - ../../base
  - ingress.yaml

# ConfigMap 生成器（合并 base 中的 configmap）
configMapGenerator:
  - name: snowy-actuator-app-config
    behavior: merge
    literals:
      - nacos.server.addr=nacos-prod.example.com:8848
      - spring.profiles.active=prod

# 镜像标签
images:
  - name: snowy-actuator-app
    newTag: latest
